### PR TITLE
Improves docs a bit

### PR DESCRIPTION
**Pull request by sobolevn**
1. Adds links to types that we are talking about
2. Adds `.. code-block:: python` in all places, otherwise this code was not highlighted on github

I really hope that RTD will build my PR to test it out, I am too lazy to test it locally 😆

### CODE REVIEW

**Comment by sobolevn** [comment]
Looks like it will 🎉

**Comment by sobolevn** [comment]
Looks like it won't 😞 
Снимок экрана 2021-07-06 в 8 38 20

**Comment by sobolevn** [comment]
Some unrelated updates:
- I am using `phantom-types` as an example of how one can work with my own project `dry-python/classes`, link: https://github.com/dry-python/classes/issues/24#issuecomment-874502820
- I am also writting an article about `phantom-types` in my blog (https://sobolevn.me/), ETA is about one month: I will send you the link

Thanks a lot for your hard work! 👍

**Comment by antonagestam** [comment]
Thanks for the patch, it's first one for this package! 🎉

Hmm, seems like the coverage setup isn't working, I'll look into it!

**Comment by antonagestam** [comment]
Thanks for the patch @sobolevn! 🍰 I switched to something more conventional for coverage reports.

**Pull request merged**
